version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    environment:
      - LEONLIB_MAINAPP_USER=${LEONLIB_MAINAPP_USER}
      - LEONLIB_CAPTCHA_SITE_KEY=${LEONLIB_CAPTCHA_SITE_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  db-data:
